import {Evento} from "./event";

export const EVENTS : Evento[] = [
  { id : 1,
    name : "Event1",
    description : "This is my event!",
    place : "Borschaga",
    eventType : 1,
    folderId : 1},
  {  id : 2,
    name : "Event2",
    description : "This is my event!",
    place : "Borschaga",
    eventType : 2,
    folderId : 1},
  {  id : 3,
    name : "Note3",
    description : "This is my note!",
    place : "Borschaga",
    eventType : 2,
    folderId : 1},
  {  id : 4,
    name : "Event4",
    description : "This is my event!",
    place : "Borschaga",
    eventType : 1,
    folderId : 1},
  {  id : 5,
    name : "Event5",
    description : "This is my event!",
    place : "Borschaga",
    eventType : 1,
    folderId : 1},
  {  id : 6,
    name : "Event6",
    description : "This is my event!",
    place : "Borschaga",
    eventType : 1,
    folderId : 1},
]
